### ISSUE TITLE
Coalesce task fails using Task Runner Explorer in VS 2017 stock install

### ISSUE THREAD

**Issue by GrantErickson** [IntelliTect/Coalesce.Starter#12]
The shell.task command of the 'coalesce' task in the gulpfile.js fails with the error below. It appears that the 0.6.0 version of gulp-shell introduced a change that caused this issue. Setting the version of gulp-shell to 0.5.2 works. 
Note the changes in 0.6.0 to the underlying start method.
https://github.com/sun-zheng-an/gulp-shell/releases/tag/0.6.0 

[06:40:02] Starting 'coalesce'...
[06:40:02] dotnet coalesce
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn dotnet coalesce ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
    at Function.Module.runMain (module.js:431:11)
    at startup (node.js:139:18)
    at node.js:999:3
Process terminated with code 1.

**Comment by GrantErickson** [comment]
@adamskt and @ascott18

**Comment by ascott18** [comment]
I would argue that this is a bug in Visual Studio, that bug being that VS bundles a somewhat old version of node with itself. https://github.com/sun-zheng-an/gulp-shell/issues/85#issuecomment-305818325. The bundled version, at least on my machine, is v5.4.1 - this version was released 2016-01-12, and isn't even an LTS release.

Our other tooling also requires modern versions of node - namely, webpack & its usage in Coalesce.Web.Vue. We could add a version check to this task in the gulpfile and error out if the node version is too old.

**Comment by GrantErickson** [comment]
To make this easy for people, we rolled back the version. If you want to update the version of node you will have to change the order VS looks for external tooling and likely recompile node-sass. 

Fixed by 1a08134c5d20f
