### ISSUE TITLE
Replace bower with npm

### ISSUE THREAD

**Issue by ascott18** [IntelliTect/Coalesce.Starter#3]
It would be very nice if we only had to deal with a single package manager. Everything we're getting from bower is available in npm - lets consolidate down to one.

This change should also be propagated to the demo project - https://github.com/IntelliTect/Coalesce/tree/2.0/src/Coalesce.Web

**Comment by adamskt** [comment]
I've been wanting to do this for awhile.  It would also make it easier to theme the bootstrap stuff if we only used the SASS template and not both.  We can also get rid of tsd.json since we are using @types in the package,json.
